export const getAdjectives = () => [
  'rapide', 'malin', 'simple', 'pratique', 'zen', 'gourmand', 'fute', 'organise',
  'efficace', 'clair', 'net', 'propre', 'leger', 'facile', 'fluide', 'compact',
  'express', 'urgent', 'improvise', 'spontane', 'prevu', 'planifie', 'prepare',
  'complet', 'minimal', 'essentiel', 'basique', 'detaille', 'precis', 'soigne',
  'economique', 'abordable', 'rentable', 'raisonnable', 'modeste', 'petit', 'grand',
  'genereux', 'copieux', 'leger', 'equilibre', 'sain', 'healthy', 'naturel', 'bio',
  'local', 'artisanal', 'fait-maison', 'maison', 'frais', 'de saison', 'estival',
  'hivernal', 'printanier', 'automnal', 'chaud', 'froid',
  'familial', 'convivial', 'festif', 'joyeux', 'calme', 'doux', 'delicieux',
  'savoureux', 'croquant', 'fondant', 'onctueux', 'epice', 'pimente', 'sucre',
  'sale', 'acidule', 'parfume', 'aromatique',
  'quotidien', 'hebdomadaire', 'mensuel', 'regulier', 'ponctuel', 'occasionnel',
  'routine', 'special', 'unique', 'surprise',
  'prioritaire', 'important', 'indispensable', 'necessaire', 'utile', 'pret',
  'disponible', 'urgent',
  'ecolo', 'durable', 'responsable', 'recyclable', 'reutilisable', 'zero-dechet',
  'anti-gaspi', 'ethique',
  'sans gluten', 'sans lactose', 'vegetarien', 'vegane', 'vegan', 'halal', 'casher',
  'proteine', 'energetique', 'allege', 'light',
  'colore', 'vif', 'brillant', 'sobre', 'chic', 'cool', 'moderne', 'classique',
  'traditionnel', 'rustique', 'elegant',
  'matinal', 'nocturne', 'tardif', 'anticipe',
  'pro', 'perso', 'prive', 'partage', 'commun', 'collectif',
  'mobile', 'nomade', 'urbain', 'campagnard',
  'ordonne', 'range', 'structure', 'methodique', 'rigoureux', 'logique',
  'creatif', 'inspire', 'astucieux', 'ingenieux',
  'calorique', 'vitamine', 'mineral', 'hydratant',
  'reconfortant', 'cocooning', 'genereux', 'gourmet', 'fine', 'raffine',
  'a emporter', 'a partager', 'a preparer', 'pret-a-manger',
  'premier', 'second', 'dernier', 'suivant',
  'propre', 'nickel', 'impeccable',
  'optimise', 'top', 'parfait', 'ideal', 'impeu', 'inratable',
  'focalise', 'cible', 'specifique', 'general',
  'matin', 'soir', 'week-end', 'semaine',
  'derniere-minute', 'minute', 'express',
  'anti-crise', 'petit-budget', 'grand-budget'
]