export const VAR_CONFIG = {
    TARGET_STORE_ID: '32d6dd89-4216-4588-a096-631bfaf5df56',
    TARGET_IMAGE_URL_ERROR: 'https://us.123rf.com/450wm/pgmart/pgmart1604/pgmart160400055/55602454-lettre-de-capital-s-des-bandes-entrelac%C3%A9es-blanches-sur-un-fond-noir-mod%C3%A8le-pour-embl%C3%A8me-logos-et.jpg',
    TARGET_HOME_URL: '/',
    TARGET_LISTING_URL: '/listing',
    TARGET_CHEAPEST_URL: '/cheapest',
    TARGET_BUILDING_URL: '/building',
    TARGET_PASSWORD: 'spy2024',
    TARGET_PASSWORD_EXPIRATION_TIME: 3600000,
    TARGET_PASSWORD_KEY: 'site-access',
    TARGET_PASSWORD_STATUS: 'granted',
    TARGET_PASSWORD_EXPIRES: 'expires',
    TARGET_NEWSLETTER_ENDPOINT: '/newsletter/subscribe',
    TARGET_PRICES_STORE_ENDPOINT: '/prices/store',
    TARGET_PRICES_SEARCH_ENDPOINT: '/prices/search',
    TARGET_PRODUCT_PRICE_ENDPOINT: '/product/price',
    TARGET_TASK_ENDPOINT: '/task',
};